### PR TITLE
Transcripts/game ofthrones

### PR DESCRIPTION
**Pull request by aman-berhe**
Just trying to see if my pull request is working with the transcript branch of game of thrones.

### CODE REVIEW

**Comment by hbredin** [comment]
`data` directory has been moved to `Plumcot/data` in branch `develop`.
Can you please move `transcripts.txt` there?

**Comment by hbredin** [comment]
Maybe this can help: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by aman-berhe** [comment]
Thanks,

On 2019-02-01 12:14, Hervé BREDIN wrote:

> Maybe this can help: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/32#issuecomment-459689631
[2]

**Comment by hbredin** [comment]
Which one of #32 and #34 should I consider? 
Could you please close the one that is no longer relevant?

**Comment by aman-berhe** [comment]
I taught I was working on one branch, I did not know I make this mistake
but it should be #34  [2] 

I am sorry for the inconvenience.

On 2019-03-14 09:15, Hervé BREDIN wrote:

> Which one of #32 [1] and #34 [2] should I consider?
> Could you please close the one that is no longer relevant? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/hbredin/pyannote-db-plumcot/pull/32
[2] https://github.com/hbredin/pyannote-db-plumcot/pull/34
[3]
https://github.com/hbredin/pyannote-db-plumcot/pull/32#issuecomment-472747035
[4]

**Comment by hbredin** [comment]
Closing at this pull request has been superseded by #34

**Pull request closed without merging**
