### PR TITLE
"Game Of Thrones" transcripts

### PR DESCRIPTION
**Pull request by aman-berhe**

### CODE REVIEW

**Comment by aman-berhe** [comment]
Noted. Thanks for the comments. I have more to push and make a request. 

Best, 

Aman

On 2019-02-25 12:12, Hervé BREDIN wrote:

> @HBREDIN requested changes on this pull request. 
> 
> Thanks a lot Aman! 
> 
> Here a few comments. 
> 
> You can safely remove transcript.txt as it is no longer needed. 
> 
> Please add the .txt extension to all transcript files. 
> 
> Also, it looks like there are two spaces between the name of the character and the actual sentence. Please make it one space. We want to make sure all files are formatted the same way... 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/34#pullrequestreview-207336124
[2]

**Comment by hbredin** [comment]
You don't have to create a new pull request for Game Of Thrones.

Just push to this `transcripts/GameOfThrones` branch and it will update the pull request.

**Comment by aman-berhe** [comment]
OK. I just tried to just push the other day and it was not showing me
the updates. 

On 2019-02-25 13:47, Hervé BREDIN wrote:

> You don't have to create a new pull request for Game Of Thrones. 
> 
> Just push to this transcripts/GameOfThrones branch and it will update the pull request. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/34#issuecomment-466998671
[2]

**Comment by hbredin** [comment]
Thanks Aman. Please follow the naming convention for transcript files.
It has to be something like `GameOfThrones.Season01.Episode01.txt`.

**Comment by aman-berhe** [comment]
OWW. I though we agreed with Leo to like this format, that is why I
changed it to this format. 

Ok. I will change it. 

Best, 

Aman

On 2019-02-27 16:37, Hervé BREDIN wrote:

> Thanks Aman. Please follow the naming convention for transcript files.
> It has to be something like GameOfThrones.Season01.Episode01.txt. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/34#issuecomment-467910215
[2]

**Comment by hbredin** [comment]
Looks like some of the files are still missing their `.txt` extension.

**Comment by aman-berhe** [comment]
Really? I will check again.

On 2019-02-28 11:28, Hervé BREDIN wrote:

> Looks like some of the files are still missing their .txt extension. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/34#issuecomment-468220921
[2]

**Comment by aman-berhe** [comment]
Yes you are right. I was trying to rename all the files and I forgot to
put .txt. I will fix it.

Best, 

Aman 

On 2019-02-28 11:30, berhe wrote:

> Really? I will check again.
> 
> On 2019-02-28 11:28, Hervé BREDIN wrote:
> 
>> Looks like some of the files are still missing their .txt extension. 
>> 
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote-db-plumcot/pull/34#issuecomment-468220921
[2]

**Comment by PaulLerner** [comment]
This was merged in https://github.com/PaulLerner/pyannote-db-plumcot/

**Pull request closed without merging**
