### PR TITLE
The charcters of the bigbang theory is added. TheBigBangTheory/charac…

### PR DESCRIPTION
**Pull request by aman-berhe**
…ters.txt is added as the specified format

### CODE REVIEW

**Comment by hbredin** [comment]
This pull request is about GameOfThrones, not TheBigBangTheory.
Please update the pull request accordingly (in particular the subdirectory name).

Also, it looks like the normalized names field in characters.txt does not follow the conventions described in the README file.

**Comment by hbredin** [comment]
characters.txt still does **not** follow [conventions](https://github.com/hbredin/pyannote.db.plumcot/tree/master/data#characterstxt) described in the README file (in particular in how normalized character names are chosen).

**Comment by hbredin** [comment]
Related questions: did you write a script to generate characters.txt that could be generalized to other series?

If so would you mind sharing it with us? (through another pull request adding a "script" directory for instance...)

**Comment by aman-berhe** [comment]
Ok. yes you are right for few of the charters the format is different
but for most of the charters specially the main charters  it is right.
The problem was some of the characters have more than one name (charter
name) and also they have neck names 

E.g. 

PETYR 'LITTLEFINGER' BAELISH,_PETYR 'LITTLEFINGER' BAELISH_,Aidan
Gillen,https://www.imdb.com/title/tt0944947/fullcredits?ref_=tt_ql_1

The first column is the character name on the page we can fix it like
this may be (PETYR_'LITTLEFINGER'_BAELISH) the italic bold letters are
the third column is the real name of the character (the one on read) we
can leave them like "PETYR 'LITTLEFINGER' BAELISH" . evry column is 
they are separated by comas. 

I don't know if I am missing something? any suggestion for names with
neck names? 

On 2018-12-20 15:42, Hervé BREDIN wrote:

> This pull request is about GameOfThrones, not TheBigBangTheory.
> Please update the pull request accordingly (in particular the subdirectory name). 
> 
> Also, it looks like the normalized names field in characters.txt does not follow the conventions described in the README file. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote.db.plumcot/pull/2#issuecomment-449020989
[2]

**Comment by aman-berhe** [comment]
Yes. I will.

On 2018-12-20 16:01, Hervé BREDIN wrote:

> Related questions: did you write a script to generate characters.txt that could be generalized to other series? 
> 
> If so would you mind sharing it with us? (through another pull request adding a "script" directory for instance...) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/hbredin/pyannote.db.plumcot/pull/2#issuecomment-449026938
[2]

**Comment by hbredin** [comment]
Closing this pull request because Léo @lgalmant did it for the whole corpus already. 
See latest version of the repo.

**Pull request closed without merging**
